FROM php:8.0-cli-bullseye

LABEL org.opencontainers.image.title="Worker"
LABEL org.opencontainers.image.description="Official build of Worker for Docker."
LABEL org.opencontainers.image.url="https://github.com/hongzhidao/worker"
LABEL org.opencontainers.image.source="https://github.com/hongzhidao/worker"
LABEL org.opencontainers.image.documentation="https://github.com/hongzhidao/worker"
LABEL org.opencontainers.image.vendor="Worker Project <hongzhidao@gmail.com>"
LABEL org.opencontainers.image.version="0.1.0"

RUN set -ex \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y ca-certificates git build-essential libpcre2-dev \
    && mkdir -p /usr/lib/worker/modules /usr/lib/worker/debug-modules \
    && git clone --depth 1 --branch 0.1.0 https://github.com/hongzhidao/worker.git worker \
    && cd worker \
    && NCPU="$(getconf _NPROCESSORS_ONLN)" \
    && DEB_HOST_MULTIARCH="$(dpkg-architecture -q DEB_HOST_MULTIARCH)" \
    && CC_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_CFLAGS_MAINT_APPEND="-Wp,-D_FORTIFY_SOURCE=2 -fPIC" dpkg-buildflags --get CFLAGS)" \
    && LD_OPT="$(DEB_BUILD_MAINT_OPTIONS="hardening=+all,-pie" DEB_LDFLAGS_MAINT_APPEND="-Wl,--as-needed -pie" dpkg-buildflags --get LDFLAGS)" \
    && CONFIGURE_ARGS="--prefix=/usr \
                --state=/var/lib/worker \
                --control=unix:/var/run/control.worker.sock \
                --pid=/var/run/worker.pid \
                --log=/var/log/worker.log \
                --tmp=/var/tmp \
                --user=worker \
                --group=worker \
                --libdir=/usr/lib/$DEB_HOST_MULTIARCH" \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modules=/usr/lib/worker/debug-modules --debug \
    && make -j $NCPU workerd \
    && install -pm755 build/workerd /usr/sbin/workerd-debug \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --ld-opt="$LD_OPT" --modules=/usr/lib/worker/modules \
    && make -j $NCPU workerd \
    && install -pm755 build/workerd /usr/sbin/workerd \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --modules=/usr/lib/worker/debug-modules --debug \
    && ./configure php \
    && make -j $NCPU php-install \
    && make clean \
    && ./configure $CONFIGURE_ARGS --cc-opt="$CC_OPT" --modules=/usr/lib/worker/modules \
    && ./configure php \
    && make -j $NCPU php-install \
    && ldd /usr/sbin/workerd | awk '/=>/{print $(NF-1)}' | while read n; do dpkg-query -S $n; done | sed 's/^\([^:]\+\):.*$/\1/' | sort | uniq > /requirements.apt

FROM php:8.0-cli-bullseye
COPY docker-entrypoint.sh /usr/local/bin/
COPY --from=BUILDER /usr/sbin/workerd /usr/sbin/workerd
COPY --from=BUILDER /usr/sbin/workerd-debug /usr/sbin/workerd-debug
COPY --from=BUILDER /usr/lib/worker/ /usr/lib/worker/
COPY --from=BUILDER /requirements.apt /requirements.apt
RUN ldconfig
RUN set -x \
    && mkdir -p /var/lib/worker/ \
    && mkdir -p /docker-entrypoint.d/ \
    && groupadd --gid 999 worker \
    && useradd \
         --uid 999 \
         --gid worker \
         --no-create-home \
         --home /nonexistent \
         --comment "worker user" \
         --shell /bin/false \
         worker \
    && apt update \
    && apt --no-install-recommends --no-install-suggests -y install curl $(cat /requirements.apt) \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /requirements.apt \
    && ln -sf /dev/stderr /var/log/worker.log

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["workerd", "--no-daemon", "--control", "unix:/var/run/control.worker.sock"]
