MODULES+=			python34
MODULE_SUFFIX_python34=		python3.4

MODULE_SUMMARY_python34=	Python 3.4 module for Worker

MODULE_VERSION_python34=	$(VERSION)
MODULE_RELEASE_python34=	1

MODULE_CONFARGS_python34=	python --config=python3.4-config
MODULE_MAKEARGS_python34=	python3.4
MODULE_INSTARGS_python34=	python3.4-install

MODULE_SOURCES_python34=	worker.example-python-app \
				worker.example-python3.4-config

BUILD_DEPENDS_python34=	python3.4-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python34)

MODULE_BUILD_DEPENDS_python34=,python3.4-dev

define MODULE_PREINSTALL_python34
	mkdir -p debian/worker-python3.4/usr/share/doc/worker-python3.4/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.4/usr/share/doc/worker-python3.4/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.4-config debian/worker-python3.4/usr/share/doc/worker-python3.4/examples/worker.config
endef
export MODULE_PREINSTALL_python34

define MODULE_POST_python34
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python34) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python34)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python34
