MODULES+=			python310
MODULE_SUFFIX_python310=		python3.10

MODULE_SUMMARY_python310=	Python 3.10 module for Worker

MODULE_VERSION_python310=	$(VERSION)
MODULE_RELEASE_python310=	1

MODULE_CONFARGS_python310=	python --config=python3.10-config
MODULE_MAKEARGS_python310=	python3.10
MODULE_INSTARGS_python310=	python3.10-install

MODULE_SOURCES_python310=	worker.example-python-app \
				worker.example-python3.10-config

BUILD_DEPENDS_python310=	python3.10-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python310)

MODULE_BUILD_DEPENDS_python310=,python3.10-dev

define MODULE_PREINSTALL_python310
	mkdir -p debian/worker-python3.10/usr/share/doc/worker-python3.10/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.10/usr/share/doc/worker-python3.10/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.10-config debian/worker-python3.10/usr/share/doc/worker-python3.10/examples/worker.config
endef
export MODULE_PREINSTALL_python310

define MODULE_POST_python310
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python310) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python310)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python310
