MODULES+=			python38
MODULE_SUFFIX_python38=		python3.8

MODULE_SUMMARY_python38=	Python 3.8 module for Worker

MODULE_VERSION_python38=	$(VERSION)
MODULE_RELEASE_python38=	1

MODULE_CONFARGS_python38=	python --config=python3.8-config
MODULE_MAKEARGS_python38=	python3.8
MODULE_INSTARGS_python38=	python3.8-install

MODULE_SOURCES_python38=	worker.example-python-app \
				worker.example-python3.8-config

BUILD_DEPENDS_python38=	python3.8-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python38)

MODULE_BUILD_DEPENDS_python38=,python3.8-dev

define MODULE_PREINSTALL_python38
	mkdir -p debian/worker-python3.8/usr/share/doc/worker-python3.8/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.8/usr/share/doc/worker-python3.8/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.8-config debian/worker-python3.8/usr/share/doc/worker-python3.8/examples/worker.config
endef
export MODULE_PREINSTALL_python38

define MODULE_POST_python38
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python38) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python38)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python38
