MODULES+=			python36
MODULE_SUFFIX_python36=		python3.6

MODULE_SUMMARY_python36=	Python 3.6 module for Worker

MODULE_VERSION_python36=	$(VERSION)
MODULE_RELEASE_python36=	1

MODULE_CONFARGS_python36=	python --config=python3.6-config
MODULE_MAKEARGS_python36=	python3.6
MODULE_INSTARGS_python36=	python3.6-install

MODULE_SOURCES_python36=	worker.example-python-app \
				worker.example-python3.6-config

BUILD_DEPENDS_python36=	python3.6-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python36)

MODULE_BUILD_DEPENDS_python36=,python3.6-dev

define MODULE_PREINSTALL_python36
	mkdir -p debian/worker-python3.6/usr/share/doc/worker-python3.6/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.6/usr/share/doc/worker-python3.6/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.6-config debian/worker-python3.6/usr/share/doc/worker-python3.6/examples/worker.config
endef
export MODULE_PREINSTALL_python36

define MODULE_POST_python36
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python36) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python36)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python36
