MODULES+=		jsc8
MODULE_SUFFIX_jsc8=	jsc8

MODULE_SUMMARY_jsc8=	Java 8 module for Worker

MODULE_VERSION_jsc8=	$(VERSION)
MODULE_RELEASE_jsc8=	1

MODULE_CONFARGS_jsc8=	java --module=java8 --home=/usr/lib/jvm/java-8-openjdk-$$\(DEB_HOST_ARCH\) --jars=/usr/share/worker-jsc-common/
MODULE_MAKEARGS_jsc8=	java8
MODULE_INSTARGS_jsc8=	java8-install

MODULE_SOURCES_jsc8=	worker.example-jsc-app \
			worker.example-jsc8-config

BUILD_DEPENDS_jsc8=	openjdk-8-jdk-headless openjdk-8-jre-headless
BUILD_DEPENDS+=		$(BUILD_DEPENDS_jsc8)

MODULE_BUILD_DEPENDS_jsc8=,openjdk-8-jdk-headless
MODULE_DEPENDS_jsc8=,openjdk-8-jre-headless,worker-jsc-common (= $(MODULE_VERSION_jsc_common)-$(MODULE_RELEASE_jsc_common)~$(CODENAME))

define MODULE_PREINSTALL_jsc8
	mkdir -p debian/worker-jsc8/usr/share/doc/worker-jsc8/examples/jsc-app
	install -m 644 -p debian/worker.example-jsc-app debian/worker-jsc8/usr/share/doc/worker-jsc8/examples/jsc-app/index.jsp
	install -m 644 -p debian/worker.example-jsc8-config debian/worker-jsc8/usr/share/doc/worker-jsc8/examples/worker.config
	install -m 644 -p src/java/README.JSR-340 debian/worker-jsc8/usr/share/doc/worker-jsc8/
endef
export MODULE_PREINSTALL_jsc8

define MODULE_POSTINSTALL_jsc8
	cd $$\(BUILDDIR_worker\) \&\& \
        DESTDIR=$$\(INSTALLDIR\) make java-shared-uninstall
endef
export MODULE_POSTINSTALL_jsc8

define MODULE_POST_jsc8
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_jsc8) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_jsc8)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8800/

Online documentation is available at https://github.com/hongzhidao/worker

NOTICE:

This version of Worker code is made available in support of the open source
development process.  This is an intermediate build made available for
testing purposes only.  This Worker code is untested and presumed incompatible
with the JSR 340 Java Servlet 3.1 specification.  You should not deploy or
write to this code.  You should instead deploy and write production
applications on pre-built binaries that have been tested and certified
to meet the JSR-340 compatibility requirements such as certified binaries
published for the JSR-340 reference implementation available at
https://javaee.github.io/glassfish/.

Redistribution of any Intermediate Build must retain this notice.

Oracle and Java are registered trademarks of Oracle and/or its affiliates.
Other names may be trademarks of their respective owners.

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_jsc8
