MODULES+=			python35
MODULE_SUFFIX_python35=		python3.5

MODULE_SUMMARY_python35=	Python 3.5 module for Worker

MODULE_VERSION_python35=	$(VERSION)
MODULE_RELEASE_python35=	1

MODULE_CONFARGS_python35=	python --config=python3.5-config
MODULE_MAKEARGS_python35=	python3.5
MODULE_INSTARGS_python35=	python3.5-install

MODULE_SOURCES_python35=	worker.example-python-app \
				worker.example-python3.5-config

BUILD_DEPENDS_python35=	python3.5-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python35)

MODULE_BUILD_DEPENDS_python35=,python3.5-dev

define MODULE_PREINSTALL_python35
	mkdir -p debian/worker-python3.5/usr/share/doc/worker-python3.5/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.5/usr/share/doc/worker-python3.5/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.5-config debian/worker-python3.5/usr/share/doc/worker-python3.5/examples/worker.config
endef
export MODULE_PREINSTALL_python35

define MODULE_POST_python35
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python35) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python35)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python35
