MODULES+=			python39
MODULE_SUFFIX_python39=		python3.9

MODULE_SUMMARY_python39=	Python 3.9 module for Worker

MODULE_VERSION_python39=	$(VERSION)
MODULE_RELEASE_python39=	1

MODULE_CONFARGS_python39=	python --config=python3.9-config
MODULE_MAKEARGS_python39=	python3.9
MODULE_INSTARGS_python39=	python3.9-install

MODULE_SOURCES_python39=	worker.example-python-app \
				worker.example-python3.9-config

BUILD_DEPENDS_python39=	python3.9-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python39)

MODULE_BUILD_DEPENDS_python39=,python3.9-dev

define MODULE_PREINSTALL_python39
	mkdir -p debian/worker-python3.9/usr/share/doc/worker-python3.9/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python3.9/usr/share/doc/worker-python3.9/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python3.9-config debian/worker-python3.9/usr/share/doc/worker-python3.9/examples/worker.config
endef
export MODULE_PREINSTALL_python39

define MODULE_POST_python39
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python39) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python39)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python39
