MODULES+=		jsc14
MODULE_SUFFIX_jsc14=	jsc14

MODULE_SUMMARY_jsc14=	Java 14 module for Worker

MODULE_VERSION_jsc14=	$(VERSION)
MODULE_RELEASE_jsc14=	1

MODULE_CONFARGS_jsc14=	java --module=java14 --home=/usr/lib/jvm/java-14-openjdk-$$\(DEB_HOST_ARCH\) --jars=/usr/share/worker-jsc-common/
MODULE_MAKEARGS_jsc14=	java14
MODULE_INSTARGS_jsc14=	java14-install

MODULE_SOURCES_jsc14=	worker.example-jsc-app \
			worker.example-jsc14-config

BUILD_DEPENDS_jsc14=	openjdk-14-jdk-headless openjdk-14-jre-headless
BUILD_DEPENDS+=		$(BUILD_DEPENDS_jsc14)

MODULE_BUILD_DEPENDS_jsc14=,openjdk-14-jdk-headless
MODULE_DEPENDS_jsc14=,openjdk-14-jre-headless,worker-jsc-common (= $(MODULE_VERSION_jsc_common)-$(MODULE_RELEASE_jsc_common)~$(CODENAME))

define MODULE_PREINSTALL_jsc14
	mkdir -p debian/worker-jsc14/usr/share/doc/worker-jsc14/examples/jsc-app
	install -m 644 -p debian/worker.example-jsc-app debian/worker-jsc14/usr/share/doc/worker-jsc14/examples/jsc-app/index.jsp
	install -m 644 -p debian/worker.example-jsc14-config debian/worker-jsc14/usr/share/doc/worker-jsc14/examples/worker.config
	install -m 644 -p src/java/README.JSR-340 debian/worker-jsc14/usr/share/doc/worker-jsc14/
endef
export MODULE_PREINSTALL_jsc14

define MODULE_POSTINSTALL_jsc14
	cd $$\(BUILDDIR_worker\) \&\& \
        DESTDIR=$$\(INSTALLDIR\) make java-shared-uninstall
endef
export MODULE_POSTINSTALL_jsc14

define MODULE_POST_jsc14
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_jsc14) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_jsc14)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8800/

Online documentation is available at https://github.com/hongzhidao/worker

NOTICE:

This version of Worker code is made available in support of the open source
development process.  This is an intermediate build made available for
testing purposes only.  This Worker code is untested and presumed incompatible
with the JSR 340 Java Servlet 3.1 specification.  You should not deploy or
write to this code.  You should instead deploy and write production
applications on pre-built binaries that have been tested and certified
to meet the JSR-340 compatibility requirements such as certified binaries
published for the JSR-340 reference implementation available at
https://javaee.github.io/glassfish/.

Redistribution of any Intermediate Build must retain this notice.

Oracle and Java are registered trademarks of Oracle and/or its affiliates.
Other names may be trademarks of their respective owners.

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_jsc14
