MODULES+=		python
MODULE_SUFFIX_python=	python

MODULE_SUMMARY_python=	Python module for Worker

MODULE_VERSION_python=	$(VERSION)
MODULE_RELEASE_python=	1

MODULE_CONFARGS_python=	python
MODULE_MAKEARGS_python=	python
MODULE_INSTARGS_python=	python-install

MODULE_SOURCES_python=	worker.example-python-app \
			worker.example-python-config

BUILD_DEPENDS_python=	python-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python)

MODULE_BUILD_DEPENDS_python=,python-dev

define MODULE_PREINSTALL_python
	mkdir -p debian/worker-python/usr/share/doc/worker-python/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python/usr/share/doc/worker-python/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python-config debian/worker-python/usr/share/doc/worker-python/examples/worker.config
endef
export MODULE_PREINSTALL_python

define MODULE_POST_python
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python
