MODULES+=			python27
MODULE_SUFFIX_python27=		python2.7

MODULE_SUMMARY_python27=	Python 2.7 module for Worker

MODULE_VERSION_python27=	$(VERSION)
MODULE_RELEASE_python27=	1

MODULE_CONFARGS_python27=	python --config=python2.7-config
MODULE_MAKEARGS_python27=	python2.7
MODULE_INSTARGS_python27=	python2.7-install

MODULE_SOURCES_python27=	worker.example-python-app \
				worker.example-python2.7-config

BUILD_DEPENDS_python27=	python2.7-dev
BUILD_DEPENDS+=		$(BUILD_DEPENDS_python27)

MODULE_BUILD_DEPENDS_python27=,python2.7-dev

define MODULE_PREINSTALL_python27
	mkdir -p debian/worker-python2.7/usr/share/doc/worker-python2.7/examples/python-app
	install -m 644 -p debian/worker.example-python-app debian/worker-python2.7/usr/share/doc/worker-python2.7/examples/python-app/wsgi.py
	install -m 644 -p debian/worker.example-python2.7-config debian/worker-python2.7/usr/share/doc/worker-python2.7/examples/worker.config
endef
export MODULE_PREINSTALL_python27

define MODULE_POST_python27
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python27) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/worker-$(MODULE_SUFFIX_python27)/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/control.worker.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python27
