#!/bin/sh

set -e

case "$1" in
    install)
        cat <<BANNER
----------------------------------------------------------------------

Thank you for installing Worker!

Additional modules are available in standalone packages.
To see the available modules, run: apt search --names-only '^worker-'

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
        ;;

    upgrade)
        ;;

    abort-upgrade)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
