MODULES+=		python
MODULE_SUFFIX_python=	python

MODULE_SUMMARY_python=	Python module for Worker

MODULE_VERSION_python=	$(VERSION)
MODULE_RELEASE_python=	1

MODULE_CONFARGS_python=	python
MODULE_MAKEARGS_python=	python
MODULE_INSTARGS_python=	python-install

MODULE_SOURCES_python=	worker.example-python-app \
			worker.example-python-config

ifeq ($(shell rpm --eval "%{?amzn}"), 1)
BUILD_DEPENDS_python=	python26-devel
else
BUILD_DEPENDS_python=	python-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python)

define MODULE_PREINSTALL_python
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python/examples/worker.config
endef
export MODULE_PREINSTALL_python

define MODULE_FILES_python
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python

define MODULE_POST_python
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python
