MODULES+=		jsc11
MODULE_SUFFIX_jsc11=	jsc11

MODULE_SUMMARY_jsc11=	Java 11 module for Worker

MODULE_VERSION_jsc11=	$(VERSION)
MODULE_RELEASE_jsc11=	1

MODULE_CONFARGS_jsc11=	java --module=java11 --home=/usr/lib/jvm/java-11 --lib-path=/usr/lib/jvm/jre-11/lib --jars=/usr/share/worker-jsc-common/
MODULE_MAKEARGS_jsc11=	java11
MODULE_INSTARGS_jsc11=	java11-install

MODULE_SOURCES_jsc11=	worker.example-jsc-app \
			worker.example-jsc11-config

BUILD_DEPENDS_jsc11=	java-11-openjdk-devel
BUILD_DEPENDS+=		$(BUILD_DEPENDS_jsc11)

define MODULE_DEFINITIONS_jsc11
Requires: worker-jsc-common == $(MODULE_VERSION_jsc_common)-$(MODULE_RELEASE_jsc_common)%{?dist}
Requires: java-11-headless
endef
export MODULE_DEFINITIONS_jsc11

define MODULE_PREINSTALL_jsc11
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-jsc11/examples/jsc-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-jsc11/examples/jsc-app/index.jsp
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-jsc11/examples/worker.config
%{__install} -m 644 -p %{bdir}/src/java/README.JSR-340 \
    %{buildroot}%{_datadir}/doc/worker-jsc11/
endef
export MODULE_PREINSTALL_jsc11

define MODULE_POSTINSTALL_jsc11
DESTDIR=%{buildroot} make java-shared-uninstall
endef
export MODULE_POSTINSTALL_jsc11

define MODULE_FILES_jsc11
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
%dir %{_datadir}/doc/worker-jsc11
%{_datadir}/doc/worker-jsc11/*
%{_datadir}/worker-jsc-common/*
endef
export MODULE_FILES_jsc11

define MODULE_POST_jsc11
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_jsc11) has been installed.

To check out the sample app, run these commands:

 sudo service worker restart
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8800/

Online documentation is available at https://github.com/hongzhidao/worker

`cat /usr/share/doc/worker-jsc11/README.JSR-340`

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_jsc11
