MODULES+=		python39
MODULE_SUFFIX_python39=	python3.9

MODULE_SUMMARY_python39=	Python 3.9 module for Worker

MODULE_VERSION_python39=	$(VERSION)
MODULE_RELEASE_python39=	1

MODULE_CONFARGS_python39=	python --config=python3.9-config
MODULE_MAKEARGS_python39=	python3.9
MODULE_INSTARGS_python39=	python3.9-install

MODULE_SOURCES_python39=	worker.example-python-app \
			worker.example-python39-config

ifneq (,$(findstring $(OSVER),opensuse-tumbleweed sles fedora amazonlinux2))
BUILD_DEPENDS_python39=	python3-devel
else
BUILD_DEPENDS_python39=	python39-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python39)

define MODULE_PREINSTALL_python39
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python39/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python39/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python39/examples/worker.config
endef
export MODULE_PREINSTALL_python39

define MODULE_FILES_python39
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python39

define MODULE_POST_python39
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python39) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python39
