MODULES+=		python34
MODULE_SUFFIX_python34=	python3.4

MODULE_SUMMARY_python34=	Python 3.4 module for Worker

MODULE_VERSION_python34=	$(VERSION)
MODULE_RELEASE_python34=	1

MODULE_CONFARGS_python34=	python --config=python3.4-config
MODULE_MAKEARGS_python34=	python3.4
MODULE_INSTARGS_python34=	python3.4-install

MODULE_SOURCES_python34=	worker.example-python-app \
			worker.example-python34-config

ifneq (,$(findstring $(OSVER),opensuse-leap sles))
BUILD_DEPENDS_python34=	python3-devel
else
BUILD_DEPENDS_python34=	python34-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python34)

define MODULE_PREINSTALL_python34
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python34/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python34/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python34/examples/worker.config
endef
export MODULE_PREINSTALL_python34

define MODULE_FILES_python34
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python34

define MODULE_POST_python34
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python34) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python34
