MODULES+=		python310
MODULE_SUFFIX_python310=	python3.10

MODULE_SUMMARY_python310=	Python 3.10 module for Worker

MODULE_VERSION_python310=	$(VERSION)
MODULE_RELEASE_python310=	1

MODULE_CONFARGS_python310=	python --config=python3.10-config
MODULE_MAKEARGS_python310=	python3.10
MODULE_INSTARGS_python310=	python3.10-install

MODULE_SOURCES_python310=	worker.example-python-app \
			worker.example-python310-config

ifneq (,$(findstring $(OSVER),opensuse-tumbleweed sles fedora amazonlinux2))
BUILD_DEPENDS_python310=	python3-devel
else
BUILD_DEPENDS_python310=	python310-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python310)

define MODULE_PREINSTALL_python310
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python310/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python310/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python310/examples/worker.config
endef
export MODULE_PREINSTALL_python310

define MODULE_FILES_python310
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python310

define MODULE_POST_python310
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python310) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python310
