MODULES+=		python37
MODULE_SUFFIX_python37=	python3.7

MODULE_SUMMARY_python37=	Python 3.7 module for Worker

MODULE_VERSION_python37=	$(VERSION)
MODULE_RELEASE_python37=	1

MODULE_CONFARGS_python37=	python --config=python3.7-config
MODULE_MAKEARGS_python37=	python3.7
MODULE_INSTARGS_python37=	python3.7-install

MODULE_SOURCES_python37=	worker.example-python-app \
			worker.example-python37-config

ifneq (,$(findstring $(OSVER),opensuse-tumbleweed sles fedora amazonlinux2))
BUILD_DEPENDS_python37=	python3-devel
else
BUILD_DEPENDS_python37=	python37-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python37)

define MODULE_PREINSTALL_python37
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python37/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python37/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python37/examples/worker.config
endef
export MODULE_PREINSTALL_python37

define MODULE_FILES_python37
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python37

define MODULE_POST_python37
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python37) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python37
