MODULES+=		python27
MODULE_SUFFIX_python27=	python2.7

MODULE_SUMMARY_python27=	Python 2.7 module for Worker

MODULE_VERSION_python27=	$(VERSION)
MODULE_RELEASE_python27=	1

MODULE_CONFARGS_python27=	python --config=python2.7-config
MODULE_MAKEARGS_python27=	python2.7
MODULE_INSTARGS_python27=	python2.7-install

MODULE_SOURCES_python27=	worker.example-python-app \
			worker.example-python27-config

ifneq (,$(findstring $(OSVER),opensuse-leap opensuse-tumbleweed sles))
BUILD_DEPENDS_python27=	python-devel
else ifneq (,$(findstring $(OSVER),fedora centos8))
BUILD_DEPENDS_python27=	python2-devel
else ifneq (,$(findstring $(OSVER),centos7 amazonlinux2))
BUILD_DEPENDS_python27=	python-devel
else
BUILD_DEPENDS_python27=	python27-devel
endif

BUILD_DEPENDS+=		$(BUILD_DEPENDS_python27)

define MODULE_DEFINITIONS_python27
%if (0%{?rhel} == 7) || (0%{?amzn} == 2)
Obsoletes: worker-python
%endif
endef
export MODULE_DEFINITIONS_python27

define MODULE_PREINSTALL_python27
%{__mkdir} -p %{buildroot}%{_datadir}/doc/worker-python27/examples/python-app
%{__install} -m 644 -p %{SOURCE100} \
    %{buildroot}%{_datadir}/doc/worker-python27/examples/python-app/wsgi.py
%{__install} -m 644 -p %{SOURCE101} \
    %{buildroot}%{_datadir}/doc/worker-python27/examples/worker.config
endef
export MODULE_PREINSTALL_python27

define MODULE_FILES_python27
%{_libdir}/worker/modules/*
%{_libdir}/worker/debug-modules/*
endef
export MODULE_FILES_python27

define MODULE_POST_python27
cat <<BANNER
----------------------------------------------------------------------

The $(MODULE_SUMMARY_python27) has been installed.

To check the sample app, run these commands:

 sudo service worker start
 cd /usr/share/doc/%{name}/examples
 sudo curl -X PUT --data-binary @worker.config --unix-socket /var/run/worker/control.sock http://localhost/config
 curl http://localhost:8400/

Online documentation is available at https://github.com/hongzhidao/worker

----------------------------------------------------------------------
BANNER
endef
export MODULE_POST_python27
